import {StyleSheet} from 'react-native'

import colors from './colors'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  defaultButton: {
    width: '60%',
    height: 40,
    backgroundColor: colors.background,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  buttonText: {
    fontSize: 16,
    fontFamily: 'bold',
  },
  labelWrapper: {
    position: 'relative',
  },
  form: {
    marginLeft: 'auto',
    marginRight: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    height: 150,
  },
  inputLabel: {
    fontFamily: 'light',
    fontSize: 16,
    position: 'absolute',
    zIndex: 100,
    top: 4,
    left: -118,
    color: colors.lightgray,
  },
  inputLabelFocused: {},
  error: {
    borderBottomWidth: 1,
    borderColor: colors.errorText,
    width: '60%',
    fontSize: 16,
    height: 30,
    paddingTop: 4,
    backgroundColor: colors.background,
  },
  input: {
    borderBottomWidth: 1,
    borderColor: colors.contrast,
    color: colors.contrast,
    width: '70%',
    fontSize: 16,
    height: 30,
    paddingTop: 4,
    backgroundColor: 'transparent',
    marginBottom: 20,
  },
  errorInput: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: colors.gray,
    color: colors.contrast,
    width: '60%',
    paddingTop: 4,
    fontSize: 16,
    height: 30,
    backgroundColor: colors.errorText,
  },
  errorText: {
    color: colors.errorText,
    textTransform: 'uppercase',
    fontSize: 12,
    width: '60%',
    fontFamily: 'light',
  },
  invisError: {
    color: colors.background,
    fontSize: 12,
    width: '60%',
    fontFamily: 'light',
    marginBottom: 5,
  },
  label: {
    color: colors.lightgray,
    textTransform: 'uppercase',
    fontSize: 12,
    width: '60%',
    fontFamily: 'light',
  },
  errorLabel: {
    color: colors.errorText,
    fontSize: 12,
    fontFamily: 'regular',
    marginBottom: 5,
  },
})
